# Generated by Django 2.2.6 on 2019-10-02 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Desafio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=30)),
                ('tema', models.CharField(max_length=15)),
                ('valor', models.TextField(max_length=240)),
                ('likes', models.PositiveIntegerField(default=0)),
                ('ativo', models.BooleanField(default=True)),
                ('criacao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.FileField(upload_to='avatar/')),
                ('nome', models.CharField(max_length=15, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('senha', models.CharField(max_length=15)),
                ('telefone', models.CharField(max_length=14)),
                ('ativo', models.BooleanField(default=True)),
                ('criacao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Resposta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.TextField(max_length=240)),
                ('likes', models.PositiveIntegerField(default=0)),
                ('ativo', models.BooleanField(default=True)),
                ('criacao', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Usuario')),
                ('desafio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='website.Desafio')),
            ],
        ),
        migrations.AddField(
            model_name='desafio',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Usuario'),
        ),
        migrations.CreateModel(
            name='Conclusao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desafio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Desafio')),
                ('resposta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Resposta')),
            ],
        ),
    ]
