# Generated by Django 2.2.6 on 2019-10-04 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='desafio',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='resposta',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
