# Generated by Django 2.2.6 on 2019-10-03 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='total',
        ),
        migrations.AddField(
            model_name='desafio',
            name='total',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
