# Generated by Django 2.2.5 on 2019-10-01 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20191001_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conclusao',
            name='desafio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Desafio'),
        ),
        migrations.AlterField(
            model_name='resposta',
            name='desafio',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='website.Desafio'),
        ),
    ]
