# Generated by Django 2.2.6 on 2019-10-03 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20191003_0232'),
    ]

    operations = [
        migrations.AddField(
            model_name='resposta',
            name='total',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
